apiVersion: v1
kind: Service
metadata:
  name: usernode-js-service
  namespace: prince
spec:
  type: ClusterIP    # Use NodePort or LoadBalancer to access application outside cluster
  ports:
    - port: 3130
      targetPort: 3130
      protocol: TCP
  selector:
    app: userprofile
